pluginManagement {
    repositories {
        // 1. 阿里云镜像放在最前面
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }

        // 2. 官方仓库作为备用
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://maven.pkg.jetbrains.space/public/p/compose/dev" }
    }
    plugins {
        id 'com.android.application' version '8.1.2' apply false
        id 'org.jetbrains.kotlin.android' version '1.9.20' apply false
        id 'org.jetbrains.compose' version '1.5.10' apply false
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        // 同样，镜像放在前面
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/google' }

        // 官方仓库备用
        google()
        mavenCentral()
    }
}

rootProject.name = "PlantKnow"
include ':app'